"""
Regenerate helpers/INDEX.md and update helpers/problem_assignments.json.

INDEX.md lists every helper function with the problems it applies to,
taken from the "Problems:" line at the end of each docstring, and every
solved problem with the helpers its solution imports.

problem_assignments.json is what the Helpers panel uses to show the helper
files for the open problem. Files a solution imports with
"from helpers.<module> import ..." are added to its problem; files you
assigned by hand in the Helpers panel are kept.

Run from the project root:
    python -m tools.build_helper_index
"""

import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HELPERS = ROOT / "helpers"
SOLUTIONS = ROOT / "solutions"


def helper_modules():
    return sorted(p.stem for p in HELPERS.glob("*.py") if not p.stem.startswith("_"))


def solved_problems():
    """Return the problem numbers that have a solution file."""
    return sorted(int(m.group(1)) for f in SOLUTIONS.glob("solution_*.py")
                  if (m := re.fullmatch(r"solution_(\d+)\.py", f.name)))


def problem_title(n):
    """Return the title from the problem's text file, or '' if not found."""
    lo = (n - 1) // 100 * 100 + 1
    path = ROOT / "problems" / f"{lo}-{lo + 99}" / f"problem_{n}.txt"
    try:
        first = path.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, IndexError):
        return ""
    return first.split(":", 1)[1].strip().replace("$", "") if ":" in first else ""


def helper_functions():
    """Return [(module, function, summary, [problems])] for every public function."""
    rows = []
    for module in helper_modules():
        tree = ast.parse((HELPERS / f"{module}.py").read_text(encoding="utf-8"))
        for node in tree.body:
            if not isinstance(node, ast.FunctionDef) or node.name.startswith("_"):
                continue
            doc = ast.get_docstring(node) or ""
            match = re.search(r"^Problems:[ \t]*(.*)$", doc, re.MULTILINE)
            problems = sorted({int(x) for x in re.findall(r"\d+", match.group(1))}) if match else []
            summary = doc.splitlines()[0] if doc else ""
            rows.append((module, node.name, summary, problems))
    return rows


def imported_helpers(n):
    """Return the helper modules that solution n imports."""
    source = (SOLUTIONS / f"solution_{n}.py").read_text(encoding="utf-8")
    modules = set(re.findall(r"^\s*from helpers\.(\w+) import", source, re.MULTILINE))
    modules |= set(re.findall(r"^\s*import helpers\.(\w+)", source, re.MULTILINE))
    return sorted(m for m in modules if (HELPERS / f"{m}.py").exists())


def write_index(rows, solved):
    by_problem = {n: [] for n in solved}
    for module, name, _, problems in rows:
        for n in problems:
            by_problem.setdefault(n, []).append(f"{module}.{name}")

    out = [
        "# Helpers index",
        "",
        "Generated by `python -m tools.build_helper_index`. Don't edit this file by hand:",
        "change the `Problems:` line in a function's docstring and run the script again.",
        "",
        "## Functions and the problems they apply to",
        "",
    ]
    if not rows:
        out.append("No helper functions yet.")
    current = None
    for module, name, summary, problems in rows:
        if module != current:
            if current is not None:
                out.append("")
            out += [f"### `helpers/{module}.py`", "",
                    "| Function | What it does | Problems |", "|---|---|---|"]
            current = module
        nums = ", ".join(map(str, problems)) or "-"
        out.append(f"| `{name}` | {summary.replace('|', '/')} | {nums} |")

    out += ["", "## Solved problems and the helpers they use", ""]
    if solved:
        out += ["| # | Title | Helper functions |", "|---|---|---|"]
        for n in solved:
            used = ", ".join(f"`{c}`" for c in by_problem.get(n, [])) or "-"
            out.append(f"| {n} | {problem_title(n)} | {used} |")
    else:
        out.append("No solutions yet.")

    path = HELPERS / "INDEX.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")


def update_assignments(solved):
    path = HELPERS / "problem_assignments.json"
    try:
        assignments = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        assignments = {}
    added = 0
    for n in solved:
        current = assignments.setdefault(str(n), [])
        for module in imported_helpers(n):
            filename = f"{module}.py"
            if filename not in current:
                current.append(filename)
                added += 1
    assignments = {k: v for k, v in assignments.items() if v}
    path.write_text(json.dumps(assignments) + "\n", encoding="utf-8")
    print(f"Updated {path.relative_to(ROOT)} ({added} new assignments)")


def main():
    solved = solved_problems()
    rows = helper_functions()
    write_index(rows, solved)
    update_assignments(solved)
    unlisted = [f"{m}.{f}" for m, f, _, p in rows if not p]
    if unlisted:
        print("Functions with no problems listed yet:", ", ".join(unlisted))


if __name__ == "__main__":
    main()
